version: '3'
services:
  database:
    container_name: database
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: directus
      MYSQL_DATABASE: directus
    ports:
      - "3306:3306"
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - directus

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: 'e640040bab73f52e9c342bed5cf0a04583ce3b70'
      SECRET: '8e73a927a627908a7325ff30bb7a39072d3bd7a8'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'root'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: '12345678'
      
      # Make sure to set this in production (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus: